/**
 * Commonwealth of Massachusetts v. Lindsay Clancy — the January 24, 2023
 * deaths of the three Clancy children in Duxbury, Massachusetts.
 *
 * ON TRIAL IN REAL LIFE AS OF THIS FILE'S LAST UPDATE (August 2026):
 * jury empaneled July 20, 2026; openings July 27, 2026; Plymouth Superior
 * Court, Sullivan, J., Docket No. 2383CR00199. Facts below are drawn from
 * the official record and public reporting of the actual proceedings —
 * the Plymouth DA's February 7, 2023 arraignment release, public motion
 * practice (bifurcation denied; reconsideration), the August 4, 2026
 * stipulation, and sworn trial testimony. Witnesses who have publicly
 * testified appear under their real names; stand-ins where the record is
 * thin are flagged "(composite)". Juror-facing material must always stay
 * outcome-blind — the real jury is out contemporaneously with this
 * simulation, and no real-world verdict may be referenced.
 *
 * NOT A DISCOVERY SUBSTITUTE: this file is an educational dramatization
 * assembled from public sources. Anyone preparing for the actual case must
 * verify every fact against the official record and their own discovery.
 */
export default {
  id: 'clancy',
  title: 'Commonwealth of Massachusetts v. Lindsay Clancy',
  jurisdiction: 'Plymouth County Superior Court, Massachusetts',
  caseNumber: 'Docket No. 2383CR00199',
  status: 'ON TRIAL in real life (jury empaneled July 2026) — simulation is outcome-blind',
  blurb:
    'A labor-and-delivery nurse strangled her three young children during a 25-minute window while her husband ran an errand — a fact she has stipulated. The only live question is the hardest one in criminal law: was she criminally responsible, or destroyed by postpartum psychosis and a thirteen-medication spiral?',
  disclaimer:
    'Educational dramatization of a case ON TRIAL in real life, based solely on the official public record and sworn public testimony. Nothing here presumes or reveals any real-world outcome. Composite witnesses are flagged. This simulation is not a substitute for the official record or discovery.',
  parties: {
    defendant: 'Lindsay Clancy, 35 (32 at the time), formerly a labor-and-delivery nurse at Massachusetts General Hospital',
    victims: ['Cora Clancy, 5', 'Dawson Clancy, 3', 'Callan Clancy, 8 months'],
    judge: 'William Sullivan',
    prosecutor: 'Assistant District Attorney Jennifer Sprague, Plymouth County',
    defenseCounsel: 'Kevin Reddington',
  },
  factSummary: `On January 24, 2023, at 47 Summer Street in Duxbury, Massachusetts, the three Clancy children were strangled with exercise bands while their father ran a brief errand. Surveillance places Patrick Clancy in the children's-medication aisle of the CVS on Summer Street in Kingston at 5:32 p.m. (buying a child's stool softener) and at the ThreeV restaurant counter at 5:54 p.m. picking up a takeout order. At approximately 6:11 p.m., Duxbury police received his 911 call — initially reporting that his wife had jumped from a window in a suicide attempt. The call ran roughly seven minutes; he can be heard telling Lindsay to "wake up," then discovering the children. First responders found Lindsay Clancy gravely injured beneath a second-story window, and the children unconscious in the basement with obvious signs of severe trauma. Cora and Dawson were pronounced dead at Beth Israel Deaconess-Plymouth that night; Callan was medflighted to Boston Children's Hospital and died three days later. Lindsay arrived at the hospital as a Level 1 trauma with a body temperature of 82.1°F, spinal injuries from the fall, and self-inflicted wounds; she is paralyzed from the waist down. In the four months before, she had been prescribed thirteen psychiatric medications by multiple providers — including Zoloft, Prozac, Klonopin, Valium, Ativan, Seroquel, Lamictal, trazodone, mirtazapine, Ambien, and Benadryl as a sedative — attended the Women's Mental Health program at Brigham and Women's, and completed a January 1-5, 2023 admission at McLean Hospital. Toxicology from the night found mirtazapine, lamotrigine, quetiapine, and trazodone in her system — at levels the Commonwealth's expert characterizes as low. She reported hearing a man's voice that day telling her it was her "last chance" to kill the children and then herself. She was arraigned February 7, 2023 from her hospital bed on three counts each of murder, strangulation, and assault and battery with a dangerous weapon, and later indicted. She was found competent after evaluation. The defense moved to bifurcate the trial — offering to stipulate to causing the deaths and try only criminal responsibility; the court denied it and denied reconsideration. At trial on August 4, 2026, she personally, knowingly, and voluntarily stipulated to the forensic facts: she caused the children's deaths. The sole live issue is criminal responsibility under the McHoul standard — whether the Commonwealth can prove beyond a reasonable doubt that she was sane. The Commonwealth's theory: she acted "deliberately and meticulously," not in the throes of psychosis. The defense: postpartum psychosis, command hallucinations, and a medication carousel that providers escalated for months without ever diagnosing the psychosis underneath.`,
  theories: {
    prosecution:
      'This mother chose the one window when no one could stop her — an errand timed to the minute — and strangled her three children one by one, then tried to leave a world she knew would hold her to account. Planning, sequencing, concealment, and a suicide attempt that presumes wrongdoing: the Commonwealth\'s experts find depression and anxiety, but the toxicology was low, the providers recorded no psychosis, and organized, goal-directed conduct is the best evidence of a mind that knew exactly what it was doing.',
    defense:
      'Lindsay Clancy begged the medical system for help for four months — thirteen medications, an emergency-room visit, a psychiatric admission — while postpartum psychosis grew underneath a treatment plan that never named it. A commanding voice told her it was her last chance. Under Massachusetts law, a person deprived by mental disease of the substantial capacity to appreciate wrongfulness or conform her conduct is not criminally responsible — and the Commonwealth cannot prove her sanity beyond a reasonable doubt on this record. She belongs in a hospital, not a prison.',
  },
  hurdles: {
    prosecution: [
      'Once lack of criminal responsibility is raised, the Commonwealth must prove SANITY beyond a reasonable doubt under McHoul — and its own treating-psychiatrist witness conceded on cross that psychotic patients can plan, communicate, and appear lucid',
      'Four months of documented, escalating treatment — thirteen medications, an ER visit, a McLean admission — corroborate genuine disease, and the stipulation stripped the trial of everything except that question',
      'Patrick Clancy has publicly forgiven her and attributes the acts to illness — the Commonwealth\'s central lay witness humanizes the defendant',
    ],
    defense: [
      'The defense must connect the psychosis to the precise moment of the killings — symptoms before and after are not enough if the jury believes the 25-minute window shows deliberate, meticulous execution',
      'Toxicology showed only low medication levels, undercutting an overmedication/intoxication theory and pushing everything onto the disputed psychosis diagnosis',
      'Her providers screened her repeatedly — including at McLean weeks earlier — and recorded no psychosis; she denied hallucinations on the instruments, so the jury may see a hindsight diagnosis built from her own post-hoc account',
    ],
  },
  charges: [
    {
      id: 'murder_cora',
      name: 'Count 1: Murder in the first degree — Cora Clancy',
      elements: [
        'The defendant unlawfully killed Cora Clancy (STIPULATED)',
        'With deliberate premeditation, or with extreme atrocity or cruelty',
        'And the defendant was criminally responsible (sane) at the time — which the Commonwealth must prove beyond a reasonable doubt',
      ],
      verdictOptions: ['guilty_of_first_degree_murder', 'guilty_of_second_degree_murder', 'not_guilty_by_reason_of_lack_of_criminal_responsibility', 'not_guilty'],
      lesserNote: 'Second-degree murder is a lesser included offense; lack of criminal responsibility (McHoul) yields commitment to a secure facility, not release.',
    },
    {
      id: 'murder_dawson',
      name: 'Count 2: Murder in the first degree — Dawson Clancy',
      elements: [
        'The defendant unlawfully killed Dawson Clancy (STIPULATED)',
        'With deliberate premeditation, or with extreme atrocity or cruelty',
        'And the defendant was criminally responsible at the time',
      ],
      verdictOptions: ['guilty_of_first_degree_murder', 'guilty_of_second_degree_murder', 'not_guilty_by_reason_of_lack_of_criminal_responsibility', 'not_guilty'],
    },
    {
      id: 'murder_callan',
      name: 'Count 3: Murder in the first degree — Callan Clancy',
      elements: [
        'The defendant unlawfully killed Callan Clancy (STIPULATED)',
        'With deliberate premeditation, or with extreme atrocity or cruelty',
        'And the defendant was criminally responsible at the time',
      ],
      verdictOptions: ['guilty_of_first_degree_murder', 'guilty_of_second_degree_murder', 'not_guilty_by_reason_of_lack_of_criminal_responsibility', 'not_guilty'],
    },
    {
      id: 'strangulation_abdw',
      name: 'Counts 4-9: Strangulation (3) and Assault & Battery with a Dangerous Weapon (3)',
      elements: [
        'The defendant strangled each child and committed assault and battery upon each with a dangerous weapon (exercise bands) (conduct STIPULATED)',
        'And the defendant was criminally responsible at the time',
      ],
      verdictOptions: ['guilty', 'not_guilty_by_reason_of_lack_of_criminal_responsibility', 'not_guilty'],
      lesserNote: 'Tried together with the murder counts; the criminal-responsibility question controls these counts equally.',
    },
  ],
  juryInstructions: `The defendant is presumed innocent; the Commonwealth must prove each element beyond a reasonable doubt. The defendant has STIPULATED that she caused the deaths of Cora, Dawson, and Callan by strangulation; you must accept those facts as proven, but the stipulation is NOT a guilty plea and is not an admission of criminal responsibility. First-degree murder requires deliberate premeditation — a decision to kill reflected upon, even briefly — or extreme atrocity or cruelty (considering factors such as the consciousness and suffering of the victims, the manner and force used, and the disproportion between the means and a resulting death). Because lack of criminal responsibility has been raised, the Commonwealth must ALSO prove beyond a reasonable doubt that the defendant was criminally responsible: that she did NOT suffer from a mental disease or defect that deprived her of the substantial capacity to appreciate the wrongfulness of her conduct or to conform her conduct to the requirements of law (the McHoul standard). Organized or goal-directed behavior does not by itself establish sanity, and a diagnosis does not by itself establish insanity — you must decide her capacity at the time of the acts. If the Commonwealth fails to prove criminal responsibility, you must find her not guilty by reason of lack of criminal responsibility, which results in commitment for treatment, not freedom — though you must decide the verdict on the law and the evidence alone. Consider each count and each child separately.`,
  witnesses: [
    { id: 'patrick', gender: 'm', name: 'Patrick Clancy', side: 'prosecution', description: 'ex-husband of the defendant, father of the children; testified over two days at the real trial', demeanor: 'shattered but composed; notably unwilling to demonize his ex-wife; the hardest witness in the case for both sides', knowledge: 'On January 24, 2023 he left home for a short errand run: surveillance shows him in the CVS children\'s-medication aisle in Kingston at 5:32 p.m. buying a child\'s stool softener, and at ThreeV restaurant at 5:54 p.m. collecting takeout. Returned to find Lindsay on the ground beneath the second-story window and called 911 at about 6:11 p.m. — a roughly seven-minute call in which he told her to "wake up," and, not realizing the line was still open, discovered the children in the basement. Watched her four-month decline: thirteen medications from multiple providers, an ER visit, the Brigham women\'s mental-health program, the January 1-5 McLean admission; she voiced fears about her own thoughts. Has publicly forgiven her and believes the woman that night was not his wife. Gave an interview to The New Yorker about her illness that the Commonwealth fought to obtain. On cross by either side he stays truthful: she functioned as a loving mother in daily life, and the errand was ordinary — she did not obviously stage it.' },
    { id: 'first_responder', gender: 'f', name: 'Sgt. Maria Coelho (composite for the responding Duxbury officers)', side: 'prosecution', description: 'Duxbury police sergeant, among the first on scene', demeanor: 'professional; testified at the real trial that "it turned very chaotic, very quickly"', knowledge: 'Responded to the 6:11 p.m. call reporting a woman who had jumped from a window at 47 Summer Street. Found the defendant conscious but gravely injured outside; the three children were located in the basement, unconscious with obvious signs of severe trauma and exercise bands at the scene. Two children were rushed to Beth Israel Deaconess-Plymouth; the infant was medflighted to Boston Children\'s. Secured the scene, which included a knife recovered near the defendant and the open second-story window. What the defendant said at the scene is limited and subject to the court\'s rulings.' },
    { id: 'trooper_oloughlin', gender: 'm', name: 'Trooper Jonathan O\'Loughlin, Massachusetts State Police', side: 'prosecution', description: 'State Police investigator; testified at the real trial on the investigation and timeline', demeanor: 'methodical, precise about times and sources', knowledge: 'Helped assemble the investigative timeline: the CVS surveillance at 5:32 p.m., ThreeV at 5:54 p.m., the 6:11 p.m. 911 call, drive times, and the resulting window of roughly 25 minutes in which the children died. Processed scene evidence and digital extractions. The defendant\'s phone contains both the evening\'s activity and months of postpartum-illness searches and help-seeking. Under the August 4, 2026 stipulation, chain-of-custody and forensic identity facts are established without dispute.' },
    { id: 'hartnett', gender: 'f', name: 'Maureen Hartnett, forensic scientist', side: 'prosecution', description: 'state crime laboratory forensic scientist; testified at the real trial', demeanor: 'clinical, exact', knowledge: 'Examined the physical evidence including the exercise bands used as ligatures and the knife recovered at the scene. No usable fingerprints were recovered from the knife or the bands — a point the stipulation ultimately made immaterial, since the defendant has stipulated she caused the deaths. Can describe the bands, their condition, and the testing performed.' },
    { id: 'carpio', gender: 'f', name: 'Dr. Cristina Carpio', side: 'prosecution', description: 'trauma surgeon who treated the defendant on arrival; testified at the real trial', demeanor: 'clinical, careful', knowledge: 'The defendant arrived as a Level 1 trauma with a body temperature of 82.1 degrees Fahrenheit, spinal injuries from the fall, and self-inflicted sharp-force wounds. Her injuries required extensive treatment and left her paralyzed from the waist down. Can speak to her physical condition, treatment, and what she was able to communicate in the hospital; her statements there are subject to the court\'s pretrial rulings.' },
    { id: 'me_clancy', gender: 'm', name: 'Dr. Howard Lin (composite for the OCME examiners)', side: 'prosecution', description: 'Office of the Chief Medical Examiner', demeanor: 'clinical, quiet', knowledge: 'The Office of the Chief Medical Examiner took jurisdiction and attributed all three deaths to ligature strangulation, consistent with the exercise bands. The mechanism requires sustained pressure over minutes per child. Cora, 5, and Dawson, 3, died January 24; Callan, 8 months, died three days later at Boston Children\'s after days of intensive care. The findings speak to mechanism and timing, not to the defendant\'s mental state. The stipulation establishes these facts without contest.' },
    { id: 'shah', gender: 'f', name: 'Dr. Sejal Shah', side: 'prosecution', description: 'Associate Chief of Psychiatry and Medicine at Brigham and Women\'s Hospital; involved in the defendant\'s perinatal psychiatric care; testified at the real trial', demeanor: 'careful academic clinician; candid under cross', knowledge: 'Familiar with the defendant\'s treatment through the Brigham women\'s mental-health pathway: escalating anxiety, insomnia, and depressive symptoms treated with a rotating medication regimen; screenings did not record psychosis. On cross-examination at the real trial she made concessions the defense values: that people experiencing psychosis can still communicate, plan, and act on plans; that they can appear lucid and hold normal conversations without visible impairment; and that the defendant was an honest patient reporting her symptoms, not someone exaggerating for legal advantage.' },
    { id: 'pros_psych', gender: 'f', name: 'Dr. Renata Molloy (composite for the Commonwealth\'s forensic psychiatric expert)', side: 'prosecution', description: 'forensic psychiatrist retained by the Commonwealth', demeanor: 'precise, unmoved, battle-tested expert', knowledge: 'Evaluated the defendant, the records, and the evidence. Concludes the evidence does not establish psychosis at the moment of the acts: the conduct was sequenced, goal-directed, and timed to a 25-minute absence, followed by a suicide attempt consistent with awareness of wrongdoing; providers assessed her repeatedly in the prior months without recording psychotic features, and she denied hallucinations on screening instruments including during the January McLean admission. The Commonwealth frames her as "not in the throes of psychosis," acting "deliberately and meticulously." Concedes postpartum psychosis exists, can wax and wane rapidly, and that retrospective certainty is impossible.' },
    { id: 'tox_expert', gender: 'm', name: 'Dr. Alan Brewer (composite for the toxicology expert)', side: 'prosecution', description: 'forensic toxicologist; the real trial heard this testimony', demeanor: 'didactic, numbers-first', knowledge: 'Testing of the defendant\'s blood and urine from the night found mirtazapine, lamotrigine, quetiapine, and trazodone. The levels were low — consistent with prescribed therapeutic use, not intoxication or overdose. Testifies the results do not support medication toxicity as a driver of the conduct. Concedes on cross that blood level is not a direct measure of central-nervous-system effect in a sleep-deprived postpartum patient on a months-long polypharmacy carousel, and that low levels equally show she was NOT sedated into incapacity — a fact each side reads its own way.' },
    { id: 'def_psych', gender: 'f', name: 'Dr. Miriam Okonjo (composite for the defense\'s forensic psychiatric expert)', side: 'defense', description: 'forensic psychiatrist specializing in perinatal psychiatry, retained by the defense', demeanor: 'compassionate authority; unshakable on the science of postpartum psychosis', knowledge: 'Evaluated the defendant extensively. Diagnoses postpartum psychosis with command hallucinations: she reported a man\'s voice telling her it was her "last chance" — kill the children so she could kill herself — a recognized psychotic structure, followed by her own suicide attempt out the window. Postpartum psychosis affects roughly 1-2 per 1,000 births, fluctuates hour to hour, and coexists with apparently organized behavior — organization does not equal sanity, a point even the Commonwealth\'s treating-psychiatrist witness conceded. The thirteen-medication history, the ER visit, the McLean admission, and the December-January deterioration were red flags of an emerging psychosis treated as mere anxiety. Opines she lacked substantial capacity under McHoul at the time of the acts. Concedes the command-hallucination account rests principally on the defendant\'s own reporting, and that connecting the psychosis to the precise moment is the contested step.' },
    { id: 'treating_np', gender: 'f', name: 'NP Sarah Bergin (composite for the outpatient prescriber)', side: 'defense', description: 'psychiatric nurse practitioner who managed the defendant\'s outpatient medications', demeanor: 'defensive about care decisions, sympathetic to the patient', knowledge: 'Managed medications through fall 2022 into January 2023 within a system where thirteen agents — including Zoloft, Prozac, Klonopin, Valium, Ativan, Seroquel, Lamictal, trazodone, mirtazapine, Ambien, and Benadryl used as a sedative — were prescribed by multiple providers over about four months. Documents escalating insomnia, anxiety, intrusive thoughts, and fear of being alone with her own mind. The defendant denied hallucinations at appointments and screened as low acute risk in January. Concedes no full psychotic-disorder workup was ever completed and that medication changes continued despite worsening.' },
    { id: 'mclean_clinician', gender: 'm', name: 'Dr. Aaron Feld (composite for the McLean program clinicians)', side: 'defense', description: 'clinician from the January 1-5, 2023 McLean Hospital admission', demeanor: 'guarded, institutional', knowledge: 'The defendant was admitted to McLean Hospital January 1-5, 2023 for worsening postpartum symptoms after months of outpatient escalation failed. She engaged in treatment, denied psychosis on screening instruments, and was discharged with an outpatient plan nineteen days before the deaths. Concedes screening relies on self-report; that emerging psychosis in high-functioning patients — particularly nurses who know the instruments — can evade detection; and that discharge did not mean she was well.' },
    { id: 'nanny', gender: 'f', name: 'The family\'s former nanny (composite name: Erin Doyle)', side: 'defense', description: 'former nanny for the Clancy children; a nanny testified at the real trial', demeanor: 'warm, grieving, protective of the children\'s memory', knowledge: 'Cared for the children and observed the household closely. The defendant confided her postpartum struggles — the sleeplessness, the anxiety, feeling unlike herself on the medications. Never saw anger toward the children; saw a mother who adored them and was frightened of what was happening to her own mind. On cross, acknowledges she was not present January 24 and cannot speak to the defendant\'s state that evening.' },
    { id: 'friend_colleague', gender: 'f', name: 'Nurse Dana Whelan (composite)', side: 'defense', description: 'labor-and-delivery colleague and close friend from MGH', demeanor: 'loyal, grieving, credible', knowledge: 'Worked beside the defendant for years; describes a gentle, devoted mother transparently proud of her children. In late 2022 watched her deteriorate — exhausted, hollow, frightened of her sleeplessness, saying the medications made her feel "not like myself"; she took leave from the unit. Never heard her express anger at the children. On cross, acknowledges she did not observe the defendant in the final days.' },
    { id: 'defendant_clancy', gender: 'f', name: 'Lindsay Clancy', side: 'defense', description: 'the defendant (testifies only if the defense calls her); at the real trial she personally affirmed the stipulation in open court', demeanor: 'flat affect broken by grief; medicated calm; answers slowly from a wheelchair', knowledge: 'Loved Cora, Dawson, and Callan more than her life. Remembers the fall of 2022 as a fog of sleeplessness, dread, and thirteen medications that made her feel unreal — appointments, the ER, Brigham, the January McLean admission. Describes the day of January 24 from inside: a man\'s voice telling her it was her last chance — kill the children so she could kill herself — and that she believed she was saving them from something worse. Remembers fragments: the bands, the basement stairs, the window. Has stipulated in open court, knowingly and voluntarily, that she caused her children\'s deaths; does not contest the forensic facts; maintains she was not herself. On cross, cannot fully explain the timing against the errand window; says the voice chose the moment.' },
  ],
  evidence: [
    { id: 'call_911', label: 'Exhibit 1: 911 call — Patrick Clancy (approx. 6:11 p.m., ~7 minutes)', desc: 'Played at the real trial: he reports the suicide attempt, tells Lindsay to "wake up," and — unaware the line is open — discovers the children', offeredBy: 'prosecution' },
    { id: 'cvs_video', label: 'Exhibit 2: CVS surveillance — Kingston, 5:32 p.m.', desc: 'Patrick Clancy in the children\'s-medication aisle buying a child\'s stool softener', offeredBy: 'prosecution' },
    { id: 'threev_video', label: 'Exhibit 3: ThreeV restaurant surveillance — 5:54 p.m.', desc: 'Patrick Clancy collecting the takeout order; anchors the ~25-minute window', offeredBy: 'prosecution' },
    { id: 'stipulation', label: 'Exhibit 4: Stipulated facts (August 4, 2026)', desc: 'The defendant\'s personal, knowing, voluntary stipulation that she caused the deaths; establishes forensic identity, chain of custody, and mechanism without contest — expressly NOT an admission of criminal responsibility', offeredBy: 'both' },
    { id: 'me_reports', label: 'Exhibit 5: Medical examiner reports (3)', desc: 'OCME findings: ligature strangulation of Cora (5), Dawson (3), and Callan (8 months, died January 27 at Boston Children\'s)', offeredBy: 'prosecution' },
    { id: 'bands', label: 'Exhibit 6: Exercise bands', desc: 'The ligatures; forensic examination recovered no usable fingerprints (immaterial after the stipulation)', offeredBy: 'prosecution' },
    { id: 'knife', label: 'Exhibit 7: Knife recovered at the scene', desc: 'Associated with the defendant\'s self-inflicted wounds; no usable fingerprints', offeredBy: 'prosecution' },
    { id: 'trauma_records', label: 'Exhibit 8: Defendant\'s trauma records', desc: 'Level 1 trauma arrival; body temperature 82.1°F; spinal injuries and sharp-force wounds; permanent paralysis', offeredBy: 'both' },
    { id: 'toxicology', label: 'Exhibit 9: Defendant\'s toxicology', desc: 'Blood/urine positive for mirtazapine, lamotrigine, quetiapine, trazodone — at low levels; each side reads this its own way', offeredBy: 'both' },
    { id: 'rx_history', label: 'Exhibit 10: Prescription history — 13 medications in ~4 months', desc: 'Zoloft, Prozac, Klonopin, Valium, Ativan, Seroquel, Lamictal, trazodone, mirtazapine, Ambien, Benadryl and others, from multiple prescribers', offeredBy: 'defense' },
    { id: 'mclean_records', label: 'Exhibit 11: McLean Hospital records — January 1-5, 2023 admission', desc: 'Psychiatric admission nineteen days before the deaths; screenings; discharge plan', offeredBy: 'defense' },
    { id: 'brigham_records', label: 'Exhibit 12: Brigham & Women\'s women\'s-mental-health records', desc: 'The perinatal psychiatric care pathway; symptoms reported; no psychosis recorded on screenings', offeredBy: 'both' },
    { id: 'provider_notes', label: 'Exhibit 13: Outpatient provider notes', desc: 'Escalating insomnia, anxiety, intrusive thoughts; medication churn; January low-risk screening', offeredBy: 'defense' },
    { id: 'statements', label: 'Exhibit 14: Post-incident statements (as admitted)', desc: 'The defendant\'s statements after the event — including her account of a voice saying it was her "last chance" — per the court\'s pretrial rulings', offeredBy: 'both' },
    { id: 'phone_data', label: 'Exhibit 15: Defendant\'s phone extraction', desc: 'The evening\'s activity and months of postpartum-illness searches and help-seeking', offeredBy: 'both' },
    { id: 'texts_patrick', label: 'Exhibit 16: Text messages between the defendant and Patrick', desc: 'Months of messages about her symptoms, fear, and treatment', offeredBy: 'defense' },
    { id: 'newyorker', label: 'Exhibit 17: Patrick Clancy\'s public statements and New Yorker interview (contested)', desc: 'His public forgiveness and account of her illness; the Commonwealth litigated to obtain the interview materials', offeredBy: 'both' },
    { id: 'jury_view', label: 'Exhibit 18: View — 47 Summer Street, Duxbury', desc: 'The real jury took a view of the home; layout of basement, stairs, and the second-story window', offeredBy: 'both' },
    { id: 'family_photos', label: 'Exhibit 19: Family photographs and videos', desc: 'The defendant caring for the children in the months before', offeredBy: 'defense' },
    { id: 'ppp_literature', label: 'Exhibit 20: Peer-reviewed literature on postpartum psychosis', desc: 'Incidence (~1-2 per 1,000 births), waxing-and-waning course, command hallucinations, infanticide risk, detection failure in high-functioning patients', offeredBy: 'defense' },
  ],
  aiPretrialMotions: {
    prosecution: [
      { id: 'p1', title: 'Motion in limine to limit "overmedication" evidence absent causation', argument: 'The defense should not parade thirteen drug names before the jury without expert testimony connecting them to this conduct — especially where the toxicology shows only low levels of four agents. Prescription counts without causation are sympathy dressed as science.', background: "Thirteen psychiatric medications were prescribed by multiple providers over four months (Zoloft, Prozac, Klonopin, Valium, Ativan, Seroquel, Lamictal, trazodone, mirtazapine, Ambien, Benadryl among them), but the night-of toxicology found only mirtazapine, lamotrigine, quetiapine, and trazodone — at low levels. For the motion: without an expert saying THIS regimen can cause THIS conduct, the pill list is prejudice; the low levels gut any intoxication theory. Against: the treatment course is inseparable from the insanity defense — the escalation itself is evidence of the disease's severity and of the system's failure to diagnose psychosis; low levels equally prove she was not sedated into incapacity." },
      { id: 'p2', title: 'Motion to admit the defendant\'s post-incident statements', argument: 'The defendant\'s statements after the event — including her account of the voice and her "last chance" — were spontaneous or made in treatment contexts, and are admissible as party admissions probative of her awareness and mental state.', background: "After the event the defendant described hearing a man's voice telling her it was her last chance — kill the children so she could kill herself. The Commonwealth wants the statements as admissions showing awareness and goal-direction; the defense wants them too, as the core evidence of command hallucinations. For admission: party admissions, spontaneous, probative either way. Against admission on the Commonwealth's framing: words from a woman with an 82-degree body temperature who had just gone out a window are symptoms, not confessions — and statements taken in the hospital raise voluntariness and Miranda issues resolved by the court's rulings." },
      { id: 'p3', title: 'Motion to admit Patrick Clancy\'s prior public statements and New Yorker interview materials', argument: 'The Commonwealth is entitled to the witness\'s prior statements about the defendant\'s condition and the events — a testifying witness cannot curate his account through the press while the jury hears only a version shaped for trial.', background: "Patrick Clancy gave a lengthy interview to The New Yorker about his ex-wife's illness and the deaths, and has publicly urged forgiveness. The Commonwealth litigated to obtain the interview materials. For admission: prior statements of a central testifying witness bear on completeness and credibility. Against: out-of-court narrative statements are hearsay beyond impeachment use, and his opinion that illness caused the acts invades the ultimate issue reserved for the experts and the jury." },
    ],
    defense: [
      { id: 'd1', title: 'Motion to suppress hospital statements to police', argument: 'Any statements taken while the defendant lay catastrophically injured — an 82-degree Level 1 trauma, medicated, immobilized, and in custody-like restraint — without valid Miranda waiver must be suppressed as involuntary.', background: "Police interaction with the defendant occurred while she was hospitalized with spinal injuries and hypothermia after the fall, gravely impaired. For suppression: no valid waiver is possible in that condition; anything obtained is involuntary. Against: she was not under formal arrest, questioning was limited, and voluntariness can be a jury question. The real court's rulings govern what 'as admitted' means in this simulation — argue within them." },
      { id: 'd2', title: 'Motion in limine to exclude gruesome scene and autopsy imagery', argument: 'The defendant has STIPULATED to causing the deaths and to the mechanism. With identity, cause, and chain of custody established, graphic imagery has no probative purpose left — only the power to make deliberation about her mental state impossible.', background: "After the August 4, 2026 stipulation, the forensic facts are established without contest. For limitation: the only remaining issue is criminal responsibility; gruesome imagery is now pure prejudice under the balancing test. Against: the Commonwealth may argue the manner of death — sustained ligature pressure on three children in sequence — bears on extreme atrocity or cruelty and on the deliberateness that criminal responsibility disputes; a stipulation does not strip the Commonwealth of its right to prove its case with some evidentiary force." },
      { id: 'd3', title: 'Motion to admit the complete mental-health treatment history', argument: 'The entire treatment course — all thirteen medications, the ER visit, the Brigham pathway, every screening, the January 1-5 McLean admission — is the res gestae of the criminal-responsibility defense and must come in without piecemeal hearsay objections; it is offered for treatment fact, not diagnosis-truth.', background: "The full record — thirteen medications from multiple prescribers, the Brigham women's-mental-health care, the McLean admission nineteen days before the deaths, screenings that never flagged psychosis — is layered with hearsay. For admission: the deterioration timeline IS the defense; fragmenting it misleads the jury. Against: the records are saturated with the defendant's self-reports — including her repeated denials of hallucinations, which the Commonwealth will emphasize — and the defense cannot claim the records' benefits while shielding their harms." },
    ],
  },
  aliases: [
    ['Lindsay Clancy', 'the defendant, Ms. L.'],
    ['Lindsay', 'Ms. L.'],
    ['Patrick Clancy', 'the husband, Mr. P.'],
    ['Patrick', 'Mr. P.'],
    ['Clancy', 'the family'],
    ['Cora', 'the eldest child'],
    ['Dawson', 'the middle child'],
    ['Callan', 'the infant'],
    ['Duxbury', 'the town'],
    ['47 Summer Street', 'the family home'],
    ['Massachusetts General Hospital', 'a major hospital'],
    ['McLean Hospital', 'a psychiatric hospital'],
    ['Brigham', 'a Boston hospital'],
    ['ThreeV', 'a local restaurant'],
    ['Sejal Shah', 'the treating psychiatrist'],
    ['William Sullivan', 'the presiding judge'],
  ],
  jurorPool: [
    { seat: 1, name: 'Arthur Pemberton', age: 66, occupation: 'retired fire captain', background: 'Ran into burning buildings for thirty years; has seen people do the unthinkable in crisis.', disposition: 'believes in duty, open to how minds break' },
    { seat: 2, name: 'Grace Nkemdirim', age: 37, occupation: 'hospital pharmacist', background: 'Fills these exact prescriptions daily; knows interaction risk tables cold.', disposition: 'laser-focused on the medication evidence' },
    { seat: 3, name: 'Sal DiBenedetto', age: 54, occupation: 'plumbing contractor', background: 'Father of four; wary of expert witnesses who charge by the hour.', disposition: 'blunt, skeptical of both hired psychiatrists' },
    { seat: 4, name: 'Hannah Ostrander', age: 31, occupation: 'new mother on leave from accounting', background: 'Eight months postpartum herself; knows the sleepless dread firsthand.', disposition: 'deep empathy, determined not to let it decide for her' },
    { seat: 5, name: 'Wendell Gray', age: 59, occupation: 'probation officer', background: 'Twenty-five years judging who is dangerous and who is sick.', disposition: 'pragmatic about accountability and treatment' },
    { seat: 6, name: 'Celia Vasquez', age: 43, occupation: 'elementary school teacher', background: 'Teaches five-year-olds; the victims\' ages sit heavy on her.', disposition: 'fights to keep grief from becoming verdict' },
    { seat: 7, name: 'Douglas Finch', age: 48, occupation: 'actuary', background: 'Prices rare events professionally; 1-2 per 1000 births is a number he can work with.', disposition: 'coldly rational, follows base rates and burdens' },
    { seat: 8, name: 'Maeve Callahan', age: 62, occupation: 'retired psychiatric nurse', background: 'Decades on inpatient wards; has seen psychosis hide inside competence.', disposition: 'authoritative on symptoms, careful not to testify herself' },
    { seat: 9, name: 'Jerome Watts', age: 35, occupation: 'freight dispatcher', background: 'Lost a cousin to suicide; thinks about what warnings get missed.', disposition: 'quiet, attentive to the treatment timeline' },
    { seat: 10, name: 'Patricia Yune', age: 51, occupation: 'small-claims mediator', background: 'Settles disputes by finding what each side must concede.', disposition: 'consensus-builder, presses for precise findings' },
    { seat: 11, name: 'Colin Brody', age: 27, occupation: 'personal trainer', background: 'Uses resistance bands professionally; the physical details are vivid to him.', disposition: 'concrete thinker, needs the mechanics to add up' },
    { seat: 12, name: 'Eleanor Sachs', age: 70, occupation: 'retired family-court clerk', background: 'A career watching families at their worst without losing faith in law.', disposition: 'measured, insists on the McHoul standard as written' },
  ],
  researchHint: 'Commonwealth v. Lindsay Clancy, Plymouth Superior 2383CR00199 — ON TRIAL as of August 2026 before Sullivan, J. Refresh testimony, rulings, and filings from official sources; NEVER surface any real-world verdict, jury developments, or media sentiment to jurors — the simulation must remain strictly outcome-blind.',
};
