/**
 * Commonwealth of Massachusetts v. Lindsay Clancy — the January 24, 2023
 * deaths of the three Clancy children in Duxbury, Massachusetts.
 *
 * ON TRIAL IN REAL LIFE AS OF THIS FILE'S LAST UPDATE (August 2026):
 * jury empaneled July 20, 2026; openings July 27, 2026; Plymouth Superior
 * Court, Sullivan, J., Docket No. 2383CR00199. Facts below are drawn from
 * the official record and public reporting of the actual proceedings —
 * the Plymouth DA's February 7, 2023 arraignment release, public motion
 * practice (bifurcation denied; reconsideration), the August 4, 2026
 * stipulation, and sworn trial testimony. Witnesses who have publicly
 * testified appear under their real names; stand-ins where the record is
 * thin are flagged "(composite)". Juror-facing material must always stay
 * outcome-blind — the real jury is out contemporaneously with this
 * simulation, and no real-world verdict may be referenced.
 *
 * NOT A DISCOVERY SUBSTITUTE: this file is an educational dramatization
 * assembled from public sources. Anyone preparing for the actual case must
 * verify every fact against the official record and their own discovery.
 */
export default {
  id: 'clancy',
  title: 'Commonwealth of Massachusetts v. Lindsay Clancy',
  jurisdiction: 'Plymouth County Superior Court, Massachusetts',
  caseNumber: 'Docket No. 2383CR00199',
  status: 'ON TRIAL in real life (jury empaneled July 2026) — simulation is outcome-blind',
  blurb:
    'A labor-and-delivery nurse strangled her three young children during a 25-minute window while her husband ran an errand — a fact she has stipulated. The only live question is the hardest one in criminal law: was she criminally responsible, or destroyed by postpartum psychosis and a thirteen-medication spiral?',
  disclaimer:
    'Educational dramatization of a case ON TRIAL in real life, based solely on the official public record and sworn public testimony. Nothing here presumes or reveals any real-world outcome. Composite witnesses are flagged. This simulation is not a substitute for the official record or discovery.',
  parties: {
    defendant: 'Lindsay Clancy, 35 (32 at the time), formerly a labor-and-delivery nurse at Massachusetts General Hospital',
    victims: ['Cora Clancy, 5', 'Dawson Clancy, 3', 'Callan Clancy, 8 months'],
    judge: 'William Sullivan',
    prosecutor: 'Assistant District Attorneys Jennifer Sprague and Shanan Buckingham, Plymouth County',
    defenseCounsel: 'Kevin Reddington',
  },
  factSummary: `On January 24, 2023, at 47 Summer Street in Duxbury, Massachusetts, the three Clancy children were strangled with exercise bands while their father ran a brief errand. Surveillance places Patrick Clancy in the children's-medication aisle of the CVS on Summer Street in Kingston at 5:32 p.m. (buying a child's stool softener) and at the ThreeV restaurant counter at 5:54 p.m. picking up a takeout order. At approximately 6:11 p.m., Duxbury police received his 911 call — initially reporting that his wife had jumped from a window in a suicide attempt. The call ran roughly seven minutes; he can be heard telling Lindsay to "wake up," then discovering the children. First responders found Lindsay Clancy gravely injured beneath a second-story window, and the children unconscious in the basement with obvious signs of severe trauma. Cora and Dawson were pronounced dead at Beth Israel Deaconess-Plymouth that night; Callan was medflighted to Boston Children's Hospital and died three days later. Lindsay arrived at the hospital as a Level 1 trauma with a body temperature of 82.1°F, spinal injuries from the fall, and self-inflicted wounds; she is paralyzed from the waist down. In the four months before, she had been prescribed thirteen psychiatric medications by multiple providers — including Zoloft, Prozac, Klonopin, Valium, Ativan, Seroquel, Lamictal, trazodone, mirtazapine, Ambien, and Benadryl as a sedative — attended the Women's Mental Health program at Brigham and Women's, and completed a January 1-5, 2023 admission at McLean Hospital. Toxicology from the night found mirtazapine, lamotrigine, quetiapine, and trazodone in her system — at levels the Commonwealth's expert characterizes as low. She reported hearing a man's voice that day telling her it was her "last chance" to kill the children and then herself. She was arraigned February 7, 2023 from her hospital bed on three counts each of murder, strangulation, and assault and battery with a dangerous weapon, and later indicted. She was found competent after evaluation. The defense moved to bifurcate the trial — offering to stipulate to causing the deaths and try only criminal responsibility; the court denied it and denied reconsideration. At trial on August 4, 2026, she personally, knowingly, and voluntarily stipulated to the forensic facts: she caused the children's deaths. The sole live issue is criminal responsibility under the McHoul standard — whether the Commonwealth can prove beyond a reasonable doubt that she was sane. The Commonwealth's theory: she acted "deliberately and meticulously," not in the throes of psychosis. The defense: postpartum psychosis, command hallucinations, and a medication carousel that providers escalated for months without ever diagnosing the psychosis underneath.`,
  theories: {
    prosecution:
      'This mother chose the one window when no one could stop her — an errand timed to the minute — and strangled her three children one by one, then tried to leave a world she knew would hold her to account. Planning, sequencing, concealment, and a suicide attempt that presumes wrongdoing: the Commonwealth\'s experts find depression and anxiety, but the toxicology was low, the providers recorded no psychosis, and organized, goal-directed conduct is the best evidence of a mind that knew exactly what it was doing.',
    defense:
      'Lindsay Clancy begged the medical system for help for four months — thirteen medications, an emergency-room visit, a psychiatric admission — while postpartum psychosis grew underneath a treatment plan that never named it. A commanding voice told her it was her last chance. Under Massachusetts law, a person deprived by mental disease of the substantial capacity to appreciate wrongfulness or conform her conduct is not criminally responsible — and the Commonwealth cannot prove her sanity beyond a reasonable doubt on this record. She belongs in a hospital, not a prison.',
  },
  hurdles: {
    prosecution: [
      'Once lack of criminal responsibility is raised, the Commonwealth must prove SANITY beyond a reasonable doubt under McHoul — and its own treating-psychiatrist witness conceded on cross that psychotic patients can plan, communicate, and appear lucid',
      'Four months of documented, escalating treatment — thirteen medications, an ER visit, a McLean admission — corroborate genuine disease, and the stipulation stripped the trial of everything except that question',
      'Patrick Clancy has publicly forgiven her and attributes the acts to illness — the Commonwealth\'s central lay witness humanizes the defendant',
    ],
    defense: [
      'The defense must connect the psychosis to the precise moment of the killings — symptoms before and after are not enough if the jury believes the 25-minute window shows deliberate, meticulous execution',
      'Toxicology showed only low medication levels, undercutting an overmedication/intoxication theory and pushing everything onto the disputed psychosis diagnosis',
      'Her providers screened her repeatedly — including at McLean weeks earlier — and recorded no psychosis; she denied hallucinations on the instruments, so the jury may see a hindsight diagnosis built from her own post-hoc account',
    ],
  },
  charges: [
    {
      id: 'murder_cora',
      name: 'Count 1: Murder in the first degree — Cora Clancy',
      elements: [
        'The defendant unlawfully killed Cora Clancy (STIPULATED)',
        'With deliberate premeditation, or with extreme atrocity or cruelty',
        'And the defendant was criminally responsible (sane) at the time — which the Commonwealth must prove beyond a reasonable doubt',
      ],
      verdictOptions: ['guilty_of_first_degree_murder', 'guilty_of_second_degree_murder', 'not_guilty_by_reason_of_lack_of_criminal_responsibility', 'not_guilty'],
      lesserNote: 'Second-degree murder is a lesser included offense; lack of criminal responsibility (McHoul) yields commitment to a secure facility, not release.',
    },
    {
      id: 'murder_dawson',
      name: 'Count 2: Murder in the first degree — Dawson Clancy',
      elements: [
        'The defendant unlawfully killed Dawson Clancy (STIPULATED)',
        'With deliberate premeditation, or with extreme atrocity or cruelty',
        'And the defendant was criminally responsible at the time',
      ],
      verdictOptions: ['guilty_of_first_degree_murder', 'guilty_of_second_degree_murder', 'not_guilty_by_reason_of_lack_of_criminal_responsibility', 'not_guilty'],
    },
    {
      id: 'murder_callan',
      name: 'Count 3: Murder in the first degree — Callan Clancy',
      elements: [
        'The defendant unlawfully killed Callan Clancy (STIPULATED)',
        'With deliberate premeditation, or with extreme atrocity or cruelty',
        'And the defendant was criminally responsible at the time',
      ],
      verdictOptions: ['guilty_of_first_degree_murder', 'guilty_of_second_degree_murder', 'not_guilty_by_reason_of_lack_of_criminal_responsibility', 'not_guilty'],
    },
    {
      id: 'strangulation_abdw',
      name: 'Counts 4-9: Strangulation (3) and Assault & Battery with a Dangerous Weapon (3)',
      elements: [
        'The defendant strangled each child and committed assault and battery upon each with a dangerous weapon (exercise bands) (conduct STIPULATED)',
        'And the defendant was criminally responsible at the time',
      ],
      verdictOptions: ['guilty', 'not_guilty_by_reason_of_lack_of_criminal_responsibility', 'not_guilty'],
      lesserNote: 'Tried together with the murder counts; the criminal-responsibility question controls these counts equally.',
    },
  ],
  juryInstructions: `The defendant is presumed innocent; the Commonwealth must prove each element beyond a reasonable doubt. The defendant has STIPULATED that she caused the deaths of Cora, Dawson, and Callan by strangulation; you must accept those facts as proven, but the stipulation is NOT a guilty plea and is not an admission of criminal responsibility. First-degree murder requires deliberate premeditation — a decision to kill reflected upon, even briefly — or extreme atrocity or cruelty (considering factors such as the consciousness and suffering of the victims, the manner and force used, and the disproportion between the means and a resulting death). Because lack of criminal responsibility has been raised, the Commonwealth must ALSO prove beyond a reasonable doubt that the defendant was criminally responsible: that she did NOT suffer from a mental disease or defect that deprived her of the substantial capacity to appreciate the wrongfulness of her conduct or to conform her conduct to the requirements of law (the McHoul standard). Organized or goal-directed behavior does not by itself establish sanity, and a diagnosis does not by itself establish insanity — you must decide her capacity at the time of the acts. If the Commonwealth fails to prove criminal responsibility, you must find her not guilty by reason of lack of criminal responsibility, which results in commitment for treatment, not freedom — though you must decide the verdict on the law and the evidence alone. Consider each count and each child separately.`,
  witnesses: [
    { id: "patrick", gender: "m", name: "Patrick Clancy", side: "prosecution", description: "ex-husband of the defendant, father of the children; the Commonwealth's first witness — two days on the stand (also on the defense list)", demeanor: "shattered but composed; notably unwilling to demonize his ex-wife; cross was deliberately gentle", knowledge: "Testified to the full timeline of January 24, 2023: Lindsay ordered takeout from ThreeV and around 5:15 p.m. texted asking him to also pick up a child's medication at CVS; when he called back \"She was pretty quiet. It sounded like she was busy.\" He reached the Kingston CVS children's-medication aisle at 5:32 p.m. and ThreeV at 5:54 p.m. Arriving home about 6 p.m., the first thing he noticed was the silence; the bedroom door was locked, and inside there was \"blood everywhere and the window was open... sprayed, almost like with a hose.\" Outside he found Lindsay injured; she told him \"I tried to kill myself,\" and when he asked where the kids were, she said the basement. He found Cora face down with an exercise band around her neck, Callan nearby, and Dawson in his office, and attempted CPR. His roughly seven-minute 911 call was played in court: \"Where are the kids, Lindsay\"; \"Did you fall out the window, Linds?... Is there something on your neck, Lindsay?\"; then \"She killed the kids!\" On her decline: she was \"extremely sleep deprived and highly anxious\" through fall 2022, anxious about returning to L&D work, rocked on the couch with her head under a pillow at her worst; he once asked \"Do you think you need to be kept away from them?\" — she said no, \"and a minute later she was making them lunch.\" \"I never saw Lindsay harm the kids.\" The day before the killings was \"one of her best days.\" During his November 2022 New York trip she was alone with the children without incident. Told The New Yorker: \"I wasn't married to a monster. I was married to someone who got sick,\" and that she said she heard a voice commanding her to kill the children. In a call with a defense-retained psychologist she said she heard a man's voice telling her to kill the kids and kill herself \"because it was her last chance\" — she had never before mentioned voices or used the word psychosis to him." },
    { id: "first_responders", gender: "f", name: "Sgt. Maria Coelho (composite for responding Duxbury police and fire: Officers Hall and Josephine, Capt. Hussey, Paramedic Stratton)", side: "prosecution", description: "first responders to 47 Summer Street; ten testified at the real trial", demeanor: "professional; the scene \"turned very chaotic very quickly\"", knowledge: "Dispatched to the 6:11 p.m. call. Officer Hall found Patrick Clancy \"yelling for help from behind the home\"; while officers treated Lindsay's wrist and neck wounds in the yard they heard Patrick screaming from the basement: \"I can't wake them up — I can't get them up!\" Officer Josephine went down and found only 8-month-old Callan with a faint pulse: \"Based on my training experience from previous incidents, I knew it wasn't going to be good.\" Fire Capt. Hussey, through a basement window, saw Patrick trying to remove an exercise band from a child's neck. Paramedic Stratton transported the infant, who never regained a pulse in her care. Cora and Dawson went to Beth Israel Deaconess-Plymouth; Callan was medflighted to Boston Children's. The scene included the exercise bands, a bloody knife, and the open second-story window." },
    { id: "oloughlin", gender: "m", name: "Trooper Jonathan O'Loughlin, Massachusetts State Police", side: "prosecution", description: "State Police investigator; testified on fingerprint examination and the investigation", demeanor: "methodical, precise", knowledge: "Examined the physical evidence for fingerprints: the knife and all three exercise bands were of \"no value\" — no usable fingerprints; the bloody knife was admitted as an exhibit from its sealed envelope. Familiar with the investigative record: 11 search warrants (299 pages, initially impounded, later unsealed) covering the home, both phones, electronics, and hospital biological samples; items seized included the exercise bands, medication bottles, computers, notebooks — one containing suicidal thoughts — a belt, bathrobe, pajamas, the knife, and material from the roof shingles below the bedroom window. Phone forensics showed she used the phone to track her medications, made searches the Commonwealth characterizes as \"researching ways to kill\" and the defense characterizes as suicide-related, and on January 24 checked Apple Maps travel time from Duxbury to ThreeV in Plymouth — the Commonwealth's inference being she knew how long she would be alone with the children. The morning of the 24th included a normal pediatrician visit for Cora and a routine call to CVS. Under the stipulation, chain-of-custody facts are established." },
    { id: "hartnett", gender: "f", name: "Maureen Hartnett, MSP crime laboratory", side: "prosecution", description: "forensic scientist; testified at the real trial", demeanor: "clinical, exact", knowledge: "Processed the defendant at both hospitals: documented red-brown stains on her hands at South Shore Hospital and took fingernail swabs at Brigham and Women's. Confirmed blood on the basement floor where Cora was found and four stains in the master bedroom; returned June 15, 2023 to test the exterior roof shingles below the bedroom window. Lab colleagues screened her blood and urine positive for five drug substances (the screen is non-quantitative). Chain of custody for the blood evidence, bands, and DNA samples is stipulated." },
    { id: "crook", gender: "f", name: "Sherri Crook, MSP bloodstain-pattern supervisor", side: "prosecution", description: "bloodstain-pattern analyst; testified at the real trial", demeanor: "technical, unadorned", knowledge: "Analyzed the bloodstain patterns: on the basement carpet near where Cora was found, a saturation stain and a transfer stain \"as something moved\"; on the bedroom nightstand, drip stains and a transfer stain from the bloody edge of the knife; a transfer stain on the window sill; and on the exterior shingles, evidence that \"something with blood on it came in contact with shingles\" — consistent with the defendant's path out the window. Cannot and does not opine on mental state." },
    { id: "carpio", gender: "f", name: "Dr. Cristina Carpio", side: "prosecution", description: "South Shore Hospital trauma surgeon who treated the defendant; testified at the real trial", demeanor: "clinical, careful", knowledge: "The defendant arrived as a Level 1 trauma with a body temperature of 82.1 degrees Fahrenheit. She had complex fractures in her spine from the jump — injuries that left her paralyzed from the waist down — while the cuts to her wrists and neck went \"through skin of exposed fat, not muscles, arteries, or tendon\": superficial, requiring no surgical treatment. Each side reads that contrast its own way: the Commonwealth as hesitation inconsistent with a committed suicide attempt; the defense as the frantic incompetence of a psychotic collapse. Dr. McDonough in the ER similarly found the lacerations superficial and non-bleeding." },
    { id: "springer", gender: "f", name: "Dr. Kimberley Springer, Office of the Chief Medical Examiner", side: "prosecution", description: "medical examiner; testified at the real trial", demeanor: "clinical, quiet; her testimony visibly affected the jury", knowledge: "Presented the autopsy findings: all three children died of ligature strangulation with the exercise bands; Callan's cause of death was \"complications of mechanical asphyxia\" — his heart was restarted at Beth Israel Deaconess-Plymouth but he had essentially no brain function, and he died three days later at Boston Children's. The mechanism requires sustained pressure over minutes per child. ER physicians testified Dawson received about forty minutes of resuscitation (\"It did not look like his heart would ever start again\"). Autopsy photographs were shown to jurors on screens only, per the court's order restricting dissemination. The findings speak to mechanism and timing, not mental state." },
    { id: "biswas", gender: "f", name: "Dr. Jhilam Biswas", side: "prosecution", description: "Brigham and Women's forensic psychiatrist who evaluated the defendant at bedside January 26, 2023; testified at the real trial", demeanor: "precise; candid about the evaluation's limits on cross", knowledge: "Conducted a 20-30 minute bedside evaluation on January 26, 2023, two days after the killings, while the defendant was intubated and answering by writing. She wrote that she was \"horrified,\" asked for an attorney, wrote \"is my body broken\" and \"are my legs straight,\" and asked about visitors and family. She appeared anxious but understood the questions; Dr. Biswas observed no signs of psychosis or hallucination during the evaluation. On cross-examination, conceded the evaluation's brevity and that orientation questions were skipped: \"We knew that she was really exhausted and anxious.\"" },
    { id: "shah", gender: "f", name: "Dr. Sejal Shah", side: "prosecution", description: "Associate Chief of Psychiatry and Medicine at Brigham and Women's; evaluated the defendant January 29-30 and February 21, 2023; testified at the real trial", demeanor: "careful academic clinician; candid under cross", knowledge: "In her evaluations days and weeks after the killings, the defendant denied suicidal or homicidal intent and denied hallucinations or delusions that day; her thought process was \"organized\" and \"goal-directed,\" her presentation \"calm and cooperative.\" On cross-examination made the concessions the defense values: agreed that \"people can communicate and plan and act on plans even if they're in the middle of a psychosis\"; agreed a psychotic person need not be \"drooling and stumbling and unable to walk and talk\"; agreed the defendant was \"an honest patient telling you what her symptoms were\" and did not exaggerate her symptoms for advantage." },
    { id: "pros_psych", gender: "f", name: "Dr. Renata Molloy (composite for the Commonwealth's retained forensic psychiatric expert)", side: "prosecution", description: "forensic psychiatrist retained by the Commonwealth", demeanor: "precise, unmoved, battle-tested expert", knowledge: "Evaluated the defendant, the records, and the evidence. Concludes the evidence does not establish psychosis at the moment of the acts: the conduct was sequenced, goal-directed, and timed to an errand window she researched herself (the Apple Maps travel-time check), followed by superficial self-inflicted cuts and a jump; treating evaluators at Brigham days later observed organized, goal-directed thinking and she denied hallucinations; her diary records despair — \"I feel like I'm drowning every day,\" \"I want to die\" — and resentment (\"I think I sort of resent my other children, because they prevent me from treating Cal like my first baby\"), which is depression, not command psychosis. The Commonwealth's framing: she acted \"intentionally, rationally, and swiftly to accomplish a very specific goal.\" Concedes postpartum psychosis exists, waxes and wanes, and that the first account of the commanding voice came within days through a defense-arranged call — retrospective certainty is impossible." },
    { id: "brower", gender: "m", name: "Justin Brower, NMS Labs forensic toxicologist", side: "prosecution", description: "toxicologist; testified at the real trial", demeanor: "didactic, numbers-first", knowledge: "Her blood contained four drugs: lamotrigine, mirtazapine, quetiapine, and trazodone. Quetiapine, the most prevalent, was roughly ten times below the toxic level; some agents were below therapeutic range. The results are inconsistent with an overdose attempt: \"Usually, people take handfuls of pills when they are trying to harm themselves and take their own life, and this is not consistent with that.\" Concedes on cross that blood level is not a direct measure of central-nervous-system effect in a sleep-deprived postpartum patient on a months-long polypharmacy regimen, and that sub-therapeutic levels equally corroborate the defense account of medication churn and under-treatment." },
    { id: "def_psych", gender: "f", name: "Dr. Miriam Okonjo (composite for the defense's forensic psychiatric expert)", side: "defense", description: "forensic psychiatrist specializing in perinatal psychiatry, retained by the defense", demeanor: "compassionate authority; unshakable on the science of postpartum psychosis", knowledge: "Evaluated the defendant extensively. Diagnoses postpartum psychosis with command hallucinations: she reported a man's voice telling her to kill the children and herself \"because it was her last chance\" — a recognized psychotic structure — followed by her own suicide attempt out the window. Postpartum psychosis affects roughly 1-2 per 1,000 births, fluctuates hour to hour, and coexists with apparently organized behavior — a point the Commonwealth's own treating psychiatrist conceded on cross: psychotic people \"can communicate and plan and act on plans.\" The thirteen-medication regimen — which the defense opening said \"caused homicidal ideation, suicidal ideation\" — the diary's \"crazy brain fog\" and drowning imagery, the December suicidal-thought entries that stopped being recorded after the January McLean admission, the sleeplessness, and sub-therapeutic drug levels are the signature of an emerging psychosis treated as mere anxiety. Opines she lacked substantial capacity under McHoul at the time of the acts. Concedes the command-hallucination account rests principally on her own reporting, first made through a defense-arranged call, and that connecting the psychosis to the precise moment is the contested step." },
    { id: "treating_np", gender: "f", name: "NP Sarah Bergin (composite for the outpatient prescribers)", side: "defense", description: "psychiatric nurse practitioner standing in for the outpatient medication managers", demeanor: "defensive about care decisions, sympathetic to the patient", knowledge: "Thirteen psychiatric medications were prescribed by multiple providers over about four months — Zoloft, Prozac, Klonopin, Valium, Ativan, Seroquel, Lamictal, trazodone, mirtazapine, Ambien, and Benadryl as a sedative among them; per the warrant records she was prescribed seven anxiety-spectrum medications at once and reportedly took four daily. The chart documents escalating insomnia, anxiety, intrusive thoughts, and fear of being alone with her own mind; her January 23 text to a colleague said she was working with a psychiatrist \"trying to find the right combo of meds.\" She denied hallucinations at appointments and screened as low acute risk in January. Concedes no full psychotic-disorder workup was ever completed and that changes continued despite worsening." },
    { id: "mclean_clinician", gender: "m", name: "Dr. Aaron Feld (composite for the McLean program clinicians)", side: "defense", description: "clinician from the January 1-5, 2023 McLean Hospital admission", demeanor: "guarded, institutional", knowledge: "The defendant was admitted to McLean Hospital January 1-5, 2023 for worsening postpartum symptoms after months of outpatient escalation failed; her daughter Cora told her preschool she \"missed her Mom\" during the admission. She engaged in treatment, denied psychosis on screening instruments, and was discharged with an outpatient plan nineteen days before the deaths. Her diary had recorded suicidal thoughts in December; after the McLean admission she stopped recording such thoughts — the defense reads concealment learned from screening, the Commonwealth reads improvement. Concedes screening relies on self-report; that emerging psychosis in high-functioning patients — particularly nurses who know the instruments — can evade detection; and that discharge did not mean she was well." },
    { id: "rossi", gender: "f", name: "Elaine Rossi", side: "defense", description: "the family's nanny September-December 2022; testified at the real trial", demeanor: "warm, grieving, protective of the children's memory", knowledge: "Cared for the children four months and observed the household closely: \"I observed a wonderful mom who loved her kids. She was concerned about their safety, and Callan eating and sleeping.\" Cora was a \"girly-girl\"; Dawson \"full of energy, rambunctious, funny, silly\"; Callan the \"sweetest, happiest baby.\" Watched Lindsay decline — significant weight loss, insomnia; Lindsay told her she \"had postpartum and couldn't sleep\" and slept in the basement; medication bottles were visible in the home. Never feared for the children or for Lindsay. On cross, acknowledges her employment ended in December and she was not present January 24." },
    { id: "hennigan", gender: "f", name: "Andrea Hennigan", side: "defense", description: "MGH labor-and-delivery colleague; testified at the real trial", demeanor: "loyal, grieving, credible", knowledge: "Worked beside the defendant on the L&D unit. By November 2022 Lindsay was in a \"difficult mental place,\" could not return to work, and described \"brain fog.\" On January 23, 2023 — the day before the killings — Lindsay texted that she was working with a psychiatrist \"trying to find the right combo of meds.\" \"Lindsay was always hopeful.\" Friends testified similarly: she texted one about \"taking meds and having dark thoughts\" while tapering and switching medications but \"never mentioned hurting herself or anyone else\"; at Cora's January birthday party she said she felt like \"a zombie.\" On cross, acknowledges she did not see the defendant in the final days and never heard threats toward the children." },
    { id: "defendant_clancy", gender: "f", name: "Lindsay Clancy", side: "defense", description: "the defendant (testifies only if the defense calls her); at the real trial she personally affirmed the stipulation in open court — her first words in public since the deaths", demeanor: "flat affect broken by grief; medicated calm; answers slowly from a wheelchair", knowledge: "Loved Cora, Dawson, and Callan more than her life. Her diary from the fall of 2022, read to the jury, records the descent: \"I feel like I'm drowning every day\"; \"I want to die\"; \"I feel completely disconnected with my baby\"; \"I'm so desperate to get a mental break from taking care of everyone that my mind is trying to find something physically wrong with me\"; \"I have crazy brain fog. I feel like I can't make a plan... I live moment to moment waiting for the next nap time\"; and the entry the Commonwealth emphasizes: \"I think I sort of resent my other children, because they prevent me from treating Cal like my first baby.\" Thirteen medications, the ER, Brigham, the January McLean admission. Describes January 24 from inside: a man's voice telling her to kill the children and herself because it was her last chance; she believed she was saving them. Remembers fragments: the bands, the basement stairs, the window. In open court on August 4, 2026, asked by Judge Sullivan whether she understood the stipulation relieved the Commonwealth of proving those facts, she answered from her wheelchair, quietly but clearly: \"Yes, your honor.\" Does not contest that she caused her children's deaths; maintains she was not herself. On cross, cannot fully explain the Apple Maps travel-time check against the errand window; says the voice chose the moment." },
  ],
  evidence: [
    { id: 'call_911', label: 'Exhibit 1: 911 call — Patrick Clancy (approx. 6:11 p.m., ~7 minutes)', desc: 'Played at the real trial: he reports the suicide attempt, tells Lindsay to "wake up," and — unaware the line is open — discovers the children', offeredBy: 'prosecution' },
    { id: 'cvs_video', label: 'Exhibit 2: CVS surveillance — Kingston, 5:32 p.m.', desc: 'Patrick Clancy in the children\'s-medication aisle buying a child\'s stool softener', offeredBy: 'prosecution' },
    { id: 'threev_video', label: 'Exhibit 3: ThreeV restaurant surveillance — 5:54 p.m.', desc: 'Patrick Clancy collecting the takeout order; anchors the ~25-minute window', offeredBy: 'prosecution' },
    { id: 'stipulation', label: 'Exhibit 4: Stipulated facts (August 4, 2026)', desc: 'The defendant\'s personal, knowing, voluntary stipulation that she caused the deaths; establishes forensic identity, chain of custody, and mechanism without contest — expressly NOT an admission of criminal responsibility', offeredBy: 'both' },
    { id: 'me_reports', label: 'Exhibit 5: Medical examiner reports (3)', desc: 'OCME findings: ligature strangulation of Cora (5), Dawson (3), and Callan (8 months, died January 27 at Boston Children\'s)', offeredBy: 'prosecution' },
    { id: 'bands', label: 'Exhibit 6: Exercise bands', desc: 'The ligatures; forensic examination recovered no usable fingerprints (immaterial after the stipulation)', offeredBy: 'prosecution' },
    { id: 'knife', label: 'Exhibit 7: Knife recovered at the scene', desc: 'Associated with the defendant\'s self-inflicted wounds; no usable fingerprints', offeredBy: 'prosecution' },
    { id: 'trauma_records', label: 'Exhibit 8: Defendant\'s trauma records', desc: 'Level 1 trauma arrival; body temperature 82.1°F; spinal injuries and sharp-force wounds; permanent paralysis', offeredBy: 'both' },
    { id: 'toxicology', label: 'Exhibit 9: Defendant\'s toxicology', desc: 'Blood/urine positive for mirtazapine, lamotrigine, quetiapine, trazodone — at low levels; each side reads this its own way', offeredBy: 'both' },
    { id: 'rx_history', label: 'Exhibit 10: Prescription history — 13 medications in ~4 months', desc: 'Zoloft, Prozac, Klonopin, Valium, Ativan, Seroquel, Lamictal, trazodone, mirtazapine, Ambien, Benadryl and others, from multiple prescribers', offeredBy: 'defense' },
    { id: 'mclean_records', label: 'Exhibit 11: McLean Hospital records — January 1-5, 2023 admission', desc: 'Psychiatric admission nineteen days before the deaths; screenings; discharge plan', offeredBy: 'defense' },
    { id: 'brigham_records', label: 'Exhibit 12: Brigham & Women\'s women\'s-mental-health records', desc: 'The perinatal psychiatric care pathway; symptoms reported; no psychosis recorded on screenings', offeredBy: 'both' },
    { id: 'provider_notes', label: 'Exhibit 13: Outpatient provider notes', desc: 'Escalating insomnia, anxiety, intrusive thoughts; medication churn; January low-risk screening', offeredBy: 'defense' },
    { id: 'statements', label: 'Exhibit 14: Post-incident statements (as admitted)', desc: 'The defendant\'s statements after the event — including her account of a voice saying it was her "last chance" — per the court\'s pretrial rulings', offeredBy: 'both' },
    { id: 'phone_data', label: 'Exhibit 15: Defendant\'s phone extraction', desc: 'The evening\'s activity and months of postpartum-illness searches and help-seeking', offeredBy: 'both' },
    { id: 'texts_patrick', label: 'Exhibit 16: Text messages between the defendant and Patrick', desc: 'Months of messages about her symptoms, fear, and treatment', offeredBy: 'defense' },
    { id: 'newyorker', label: 'Exhibit 17: Patrick Clancy\'s public statements and New Yorker interview (contested)', desc: 'His public forgiveness and account of her illness; the Commonwealth litigated to obtain the interview materials', offeredBy: 'both' },
    { id: 'jury_view', label: 'Exhibit 18: View — 47 Summer Street, Duxbury', desc: 'The real jury took a view of the home; layout of basement, stairs, and the second-story window', offeredBy: 'both' },
    { id: 'family_photos', label: 'Exhibit 19: Family photographs and videos', desc: 'The defendant caring for the children in the months before', offeredBy: 'defense' },
    { id: 'ppp_literature', label: 'Exhibit 20: Peer-reviewed literature on postpartum psychosis', desc: 'Incidence (~1-2 per 1,000 births), waxing-and-waning course, command hallucinations, infanticide risk, detection failure in high-functioning patients', offeredBy: 'defense' },
  ],
  aiPretrialMotions: {
    prosecution: [
      { id: 'p1', title: 'Motion in limine to limit "overmedication" evidence absent causation', argument: 'The defense should not parade thirteen drug names before the jury without expert testimony connecting them to this conduct — especially where the toxicology shows only low levels of four agents. Prescription counts without causation are sympathy dressed as science.', background: "Thirteen psychiatric medications were prescribed by multiple providers over four months (Zoloft, Prozac, Klonopin, Valium, Ativan, Seroquel, Lamictal, trazodone, mirtazapine, Ambien, Benadryl among them), but the night-of toxicology found only mirtazapine, lamotrigine, quetiapine, and trazodone — at low levels. For the motion: without an expert saying THIS regimen can cause THIS conduct, the pill list is prejudice; the low levels gut any intoxication theory. Against: the treatment course is inseparable from the insanity defense — the escalation itself is evidence of the disease's severity and of the system's failure to diagnose psychosis; low levels equally prove she was not sedated into incapacity." },
      { id: 'p2', title: 'Motion to admit the defendant\'s post-incident statements', argument: 'The defendant\'s statements after the event — including her account of the voice and her "last chance" — were spontaneous or made in treatment contexts, and are admissible as party admissions probative of her awareness and mental state.', background: "After the event the defendant described hearing a man's voice telling her it was her last chance — kill the children so she could kill herself. The Commonwealth wants the statements as admissions showing awareness and goal-direction; the defense wants them too, as the core evidence of command hallucinations. For admission: party admissions, spontaneous, probative either way. Against admission on the Commonwealth's framing: words from a woman with an 82-degree body temperature who had just gone out a window are symptoms, not confessions — and statements taken in the hospital raise voluntariness and Miranda issues resolved by the court's rulings." },
      { id: 'p3', title: 'Motion to admit Patrick Clancy\'s prior public statements and New Yorker interview materials', argument: 'The Commonwealth is entitled to the witness\'s prior statements about the defendant\'s condition and the events — a testifying witness cannot curate his account through the press while the jury hears only a version shaped for trial.', background: "Patrick Clancy gave a lengthy interview to The New Yorker about his ex-wife's illness and the deaths, and has publicly urged forgiveness. The Commonwealth litigated to obtain the interview materials. For admission: prior statements of a central testifying witness bear on completeness and credibility. Against: out-of-court narrative statements are hearsay beyond impeachment use, and his opinion that illness caused the acts invades the ultimate issue reserved for the experts and the jury." },
    ],
    defense: [
      { id: 'd1', title: 'Motion to suppress hospital statements to police', argument: 'Any statements taken while the defendant lay catastrophically injured — an 82-degree Level 1 trauma, medicated, immobilized, and in custody-like restraint — without valid Miranda waiver must be suppressed as involuntary.', background: "Police interaction with the defendant occurred while she was hospitalized with spinal injuries and hypothermia after the fall, gravely impaired. For suppression: no valid waiver is possible in that condition; anything obtained is involuntary. Against: she was not under formal arrest, questioning was limited, and voluntariness can be a jury question. The real court's rulings govern what 'as admitted' means in this simulation — argue within them." },
      { id: 'd2', title: 'Motion in limine to exclude gruesome scene and autopsy imagery', argument: 'The defendant has STIPULATED to causing the deaths and to the mechanism. With identity, cause, and chain of custody established, graphic imagery has no probative purpose left — only the power to make deliberation about her mental state impossible.', background: "After the August 4, 2026 stipulation, the forensic facts are established without contest. For limitation: the only remaining issue is criminal responsibility; gruesome imagery is now pure prejudice under the balancing test. Against: the Commonwealth may argue the manner of death — sustained ligature pressure on three children in sequence — bears on extreme atrocity or cruelty and on the deliberateness that criminal responsibility disputes; a stipulation does not strip the Commonwealth of its right to prove its case with some evidentiary force." },
      { id: 'd3', title: 'Motion to admit the complete mental-health treatment history', argument: 'The entire treatment course — all thirteen medications, the ER visit, the Brigham pathway, every screening, the January 1-5 McLean admission — is the res gestae of the criminal-responsibility defense and must come in without piecemeal hearsay objections; it is offered for treatment fact, not diagnosis-truth.', background: "The full record — thirteen medications from multiple prescribers, the Brigham women's-mental-health care, the McLean admission nineteen days before the deaths, screenings that never flagged psychosis — is layered with hearsay. For admission: the deterioration timeline IS the defense; fragmenting it misleads the jury. Against: the records are saturated with the defendant's self-reports — including her repeated denials of hallucinations, which the Commonwealth will emphasize — and the defense cannot claim the records' benefits while shielding their harms." },
    ],
  },
  publicRecord: [
    { type: "document", title: "Unsealed search-warrant records — 11 warrants, 299 pages", date: "Jan. 2023, unsealed spring 2023", source: "https://www.cbsnews.com/boston/news/search-warrants-lindsay-clancy-duxbury/", points: ["Targets: the 47 Summer St. home, Lindsay's and Patrick's phones, computers/electronics, and her hospital biological samples", "Seized: exercise bands, medication bottles, computers, notebooks, phones, a belt, bathrobe, pajamas, a silver knife, blood/urine samples, and material from the roof shingles below the bedroom window", "A notebook containing suicidal thoughts drove the electronics warrants; she had seven prescribed anxiety-spectrum medications and reportedly took four daily", "Phone evidence per the documents: she tracked her medications and made searches characterized as 'researching ways to kill'; on Jan. 24 she checked Apple Maps travel time from Duxbury to ThreeV — 'so she knew how long she would be alone with the children'", "Jan. 24 timeline: morning pediatrician visit for Cora; call to CVS; takeout ordered; texts asking Patrick to get food and medication"] },
    { type: "proceeding", title: "Arraignment — Commonwealth's statement (ADA Sprague)", date: "Feb. 7, 2023", source: "https://www.boston.com/news/local-news/2023/02/07/lindsay-clancy-duxbury-mom-arraignment-accused-murder-kids/", points: ["In a call with Patrick and a defense-retained psychologist, Lindsay said she 'heard a man's voice telling her to kill the kids and kill herself, because it was her last chance'; Patrick said she had never mentioned voices or used the word 'psychosis'", "Journal entry quoted: 'I think I sort of resent my other children, because they prevent me from treating Cal like my first baby'; suicidal thoughts documented in December, no longer recorded after the January McLean admission", "Lindsay suggested ThreeV and researched the travel time; 'When he arrived home, the first thing he noticed was the silence'", "Defense (Reddington): 'worsening depression,' 'wasn't sleeping'; displayed a 'wish vase' of notes hoping for her children's happiness; held without bail at the hospital (Canavan, J.)"] },
    { type: "proceeding", title: "Commitment and competency posture", date: "2023-2024", source: "https://www.nbcboston.com/news/local/lindsay-clancy-to-remain-at-tewksbury-hospital-for-6-months-after-section-18-hearing/3042645/", points: ["Psychiatric examination ordered; transferred from Spaulding rehab to state-run Tewksbury Hospital about May 1, 2023", "After a Section 18 hearing (May 11, 2023), committed to Tewksbury for six months; she has remained there through trial", "No public order ever found her incompetent; Sullivan, J. found her competent at the Aug. 4, 2026 stipulation colloquy", "May 2024: court-authorized DNA buccal swab collected at Tewksbury"] },
    { type: "document", title: "Order to Conde Nast / The New Yorker — Patrick Clancy interview materials", date: "Feb. 2025", source: "https://www.boston25news.com/news/local/judge-orders-new-yorker-hand-over-recordings-interview-with-lindsay-clancys-husband/OCOLWGLAOBAYFM6T3ZKFJFGH2E/", points: ["Sullivan, J. ordered production of recordings/notes of Eren Orbey's interviews for the October 2024 New Yorker article", "Commonwealth's theory: Lindsay never spoke to law enforcement, so Patrick's accounts of her statements are material to her state of mind; New York shield-law issues argued", "Article statements at issue: 'I wasn't married to a monster. I was married to someone who got sick,' and his account that she 'heard a voice commanding her to kill the children'"] },
    { type: "document", title: "Bifurcation motion — DENIED", date: "hearing Mar. 2, 2026; denied Mar. 31, 2026", source: "https://www.nbcboston.com/news/local/lindsay-clancy-murder-case-judge-issues-key-ruling/3925435/", points: ["Defense sought a two-phase trial (guilt, then criminal responsibility), citing the Fifth Amendment and offering to stipulate to involvement", "Sullivan, J.: splitting the evidence would be 'nearly impossible' and duplicative — 'These are overlapping issues that do not require bifurcation'", "Reddington publicly framed the defense: 'She takes responsibility... She owns it. She's not running away from anything here'"] },
    { type: "document", title: "Motion for reconsideration of bifurcation denial", date: "spring 2026", source: "https://www.scribd.com/document/1023188039/Lindsay-Clancy-motion-for-reconsideration", points: ["Asks the court to revisit the denial: she 'is willing to stipulate her involvement in the deaths of three children,' so 'the only issue for trial should be her state of mind'", "Denial stood; the Aug. 4, 2026 in-court stipulation functioned as a partial substitute"] },
    { type: "document", title: "Pretrial evidentiary rulings / motions in limine", date: "June 17 - July 24, 2026", source: "https://www.wbur.org/news/2026/07/27/lindsay-clancy-trial-opening-statements", points: ["Commonwealth motions: 911 call as excited utterance (admitted June 29 with limiting instruction); photos of the children in life; autopsy photos (in-camera review); bloodstain-pattern demonstration; jury view of the home, CVS, and restaurant (approved)", "Lay witnesses barred from offering medical/psychiatric opinions", "July 24 (on Patrick's motion): 911 audio and autopsy photos may be presented in court but not broadcast, recorded, or distributed; trial otherwise livestreamed", "July 20: four additional defense experts conditionally excluded pending trial developments; further defense-expert hearing held Aug. 6"] },
    { type: "testimony", title: "Day 1 — Opening statements; Patrick Clancy direct", date: "July 27, 2026", source: "https://www.wbur.org/news/2026/07/27/lindsay-clancy-trial-father-testimony", points: ["ADA Shanan Buckingham: 'They were strangled — deliberately and meticulously killed by this defendant'; 'This is a woman who acted intentionally, rationally, and swiftly to accomplish a very specific goal – to kill'", "Buckingham: 'After only four months in treatment, she made a deliberate choice... And because no one could take care of her kids the way she wanted them to, she had to take them with her'", "Reddington: she was 'suffering from psychosis'; 13 medications 'caused homicidal ideation, suicidal ideation'; 'She knows that she killed those children... the issue for consideration is what was going on in that woman's mind?'", "Patrick: fall 2022 decline, 'extremely sleep deprived and highly anxious'; 'Do you think you need to be kept away from them?' — 'No'... 'a minute later she was making them lunch'; 'I never saw Lindsay harm the kids'"] },
    { type: "testimony", title: "Day 2 — Patrick Clancy: 911 call and cross; CVS and restaurant witnesses", date: "July 29, 2026", source: "https://www.cbsnews.com/boston/live-updates/lindsay-clancy-trial-live-updates-patrick-clancy-day-2/", points: ["911 call played (courtroom only): 'Where are the kids, Lindsay'; 'Did you fall out the window, Linds?... Is there something on your neck, Lindsay?'; then 'She killed the kids!' — Lindsay wept and was wheeled out", "Timeline: ~5:15 p.m. text asking him to add the CVS stop; on his call back 'She was pretty quiet. It sounded like she was busy'; home ~6 p.m. — silence, locked bedroom door, 'blood everywhere and the window was open... sprayed, almost like with a hose'", "She told him 'I tried to kill myself'; the children were in the basement — Cora face down with a band around her neck, Callan nearby, Dawson in his office; he attempted CPR", "Cross (deliberately gentle): dedicated mother; journals showed 'horrible intrusive thoughts' while medicated; November NY trip — she was alone with the children, nothing happened; defense framed her searches as suicide-related", "CVS manager Angela Krause: the medication call was 'a very normal interaction'; ThreeV hostess: normal takeout order"] },
    { type: "testimony", title: "Day 3 — First responders (10 witnesses)", date: "July 30, 2026", source: "https://www.wbur.org/news/2026/07/30/lindsay-clancy-trial-first-responders", points: ["Officer Hall found Patrick 'yelling for help from behind the home'; officers heard him from the basement: 'I can't wake them up — I can't get them up!'", "Officer Josephine found only Callan with a faint pulse: 'Based on my training experience from previous incidents, I knew it wasn't going to be good'", "Fire Capt. Hussey saw Patrick trying to remove an exercise band from a child's neck through a basement window; the scene 'turned very chaotic very quickly'", "Paramedic Stratton: the infant never regained a pulse in her care"] },
    { type: "proceeding", title: "Day 4 — Jury view; ER physicians; hospital-watch officers", date: "July 31, 2026", source: "https://www.cbsnews.com/boston/news/lindsay-clancy-trial-day-4-jury-view-home-duxbury/", points: ["Jury view: ThreeV, the Kingston CVS, and the Duxbury home — jurors walked the basement and both floors under police supervision", "Dr. Tenerowicz (treated Dawson): 'It did not look like his heart would ever start again' — about 40 minutes of resuscitation", "Dr. Kaufman (treated Callan): restarted the infant's heart but found essentially no brain function; airlifted to Boston Children's", "Hospital watch: Lindsay 'sedated and unconscious with several lacerations to her arms and neck'; flown to Brigham"] },
    { type: "testimony", title: "Day 5 — Treating clinicians; diary read to jury; Drs. Biswas and Shah", date: "Aug. 3, 2026", source: "https://abc7chicago.com/post/lindsay-clancy-trial-today-murder-continues-diary-chronicled-desperation-brain-fog-before-she-killed-3-kids/19629861/", points: ["Diary excerpts read by ADA Buckingham: 'I feel like I'm drowning every day'; 'I want to die'; 'I feel completely disconnected with my baby'; 'I have crazy brain fog. I feel like I can't make a plan... I live moment to moment waiting for the next nap time'", "Dr. Biswas (bedside, Jan. 26, ~20-30 min, defendant intubated, writing answers): wrote she was 'horrified,' asked for an attorney, wrote 'is my body broken'; no observed psychosis; on cross conceded brevity and skipped orientation questions", "Dr. Shah (Jan. 29/30, Feb. 21): denied hallucinations/delusions; thought process 'organized' and 'goal-directed'; 'calm and cooperative'"] },
    { type: "testimony", title: "Dr. Shah cross-examination concessions", date: "Aug. 3-4, 2026", source: "https://www.foxnews.com/us/lindsay-clancy-defense-scores-extremely-helpful-psychosis-concession-expert-flags-next-hurdle", points: ["Reddington: 'People can communicate and plan and act on plans even if they're in the middle of a psychosis, right?' — Shah agreed; also agreed a psychotic person need not be 'drooling and stumbling and unable to walk and talk'", "Shah agreed Clancy was 'an honest patient telling you what her symptoms were' and did not exaggerate", "Defense-bar analysis: 'extremely helpful to the defense' — but the defense must still tie the psychosis to the time of the deaths"] },
    { type: "proceeding", title: "Stipulation and colloquy; crime-lab testimony", date: "Aug. 4, 2026", source: "https://www.bostonglobe.com/2026/08/04/metro/lindsay-clancy-trial-witnesses/", points: ["Stipulated: chain of custody and foundational facts for the physical evidence — blood, the exercise bands, DNA — eliminating dozens of foundation witnesses", "Sullivan, J.: 'Do you understand that by signing the stipulation, you're agreeing that the commonwealth does not have to prove these certain facts...?' Clancy, from her wheelchair: 'Yes, your honor' — found knowing, intelligent, voluntary; her first words in open court", "Dr. Carpio: complex spine fractures; cuts 'through skin of exposed fat, not muscles, arteries, or tendon' — superficial", "Trooper O'Loughlin: knife and all three bands 'no value' for prints; Hartnett: stains on her hands, basement blood where Cora was found, four bedroom stains, June 2023 shingle testing; Crook (bloodstain patterns): saturation/transfer stains, knife-edge transfer on the nightstand, window-sill and shingle transfers"] },
    { type: "testimony", title: "Day 7 — Former nanny; forensic toxicologist", date: "Aug. 5, 2026", source: "https://www.pbs.org/newshour/nation/former-clancy-nanny-testifies-about-mothers-mental-health-issues-before-killings", points: ["Elaine Rossi (nanny, Sept.-Dec. 2022): 'I observed a wonderful mom who loved her kids'; watched the decline — weight loss, insomnia, sleeping in the basement — yet never feared for the children", "Justin Brower (NMS Labs): four drugs in her blood — lamotrigine, mirtazapine, quetiapine, trazodone; quetiapine ~10x below toxic level; 'Usually, people take handfuls of pills when they are trying to harm themselves... this is not consistent with that'", "The low levels cut both ways: against an overdose narrative, and for the defense account of sub-therapeutic dosing and medication churn"] },
    { type: "testimony", title: "Day 8 — Medical examiner; family, friends, teachers, pediatrician", date: "Aug. 6, 2026", source: "https://www.boston25news.com/news/local/lindsay-clancy-trial-live-updates-medical-examiner-testify-about-deaths-3-young-kids/ORMYDXSPZZCP5H3FNZ45ZTAMYU/", points: ["Dr. Kimberley Springer (OCME): Callan died of 'complications of mechanical asphyxia'; autopsy photos on juror-only screens; Clancy 'inconsolable' — recess taken", "Christopher Clancy (ex-father-in-law): 'an all-American family'; Lindsay 'a little quiet' with 'a blank stare' at Thanksgiving; grandparents' overnight offer declined", "Friends: texts about 'taking meds and having dark thoughts' but 'She never mentioned hurting herself or anyone else'; she felt like 'a zombie' at Cora's birthday party", "Pediatrician: Cora's physical the morning of Jan. 24 was 'a very normal visit'", "Det. Chiachio introduced a May 2021 Facebook post calling Dawson 'the most difficult human I have ever encountered'; cross: a search of everything for evidence of abuse 'found nothing'"] },
    { type: "document", title: "SJC: Commonwealth v. Latarsha Sanders — appellate flag", date: "Aug. 6, 2026", source: "https://www.bostonglobe.com/2026/08/06/metro/lindsay-clancy-latarsha-sanders/", points: ["The SJC vacated first-degree murder convictions in an insanity-defense case, holding the trial judge — the same Judge William F. Sullivan — erred in excluding psychiatric records", "Live appellate-issue flag for both trial teams: same judge, same defense theory, same category of contested psychiatric-records evidence"] },
  ],
  aliases: [
    ['Lindsay Clancy', 'the defendant, Ms. L.'],
    ['Lindsay', 'Ms. L.'],
    ['Patrick Clancy', 'the husband, Mr. P.'],
    ['Patrick', 'Mr. P.'],
    ['Clancy', 'the family'],
    ['Cora', 'the eldest child'],
    ['Dawson', 'the middle child'],
    ['Callan', 'the infant'],
    ['Duxbury', 'the town'],
    ['47 Summer Street', 'the family home'],
    ['Massachusetts General Hospital', 'a major hospital'],
    ['McLean Hospital', 'a psychiatric hospital'],
    ['Brigham', 'a Boston hospital'],
    ['ThreeV', 'a local restaurant'],
    ['Sejal Shah', 'the treating psychiatrist'],
    ['William Sullivan', 'the presiding judge'],
  ],
  jurorPool: [
    { seat: 1, name: 'Arthur Pemberton', age: 66, occupation: 'retired fire captain', background: 'Ran into burning buildings for thirty years; has seen people do the unthinkable in crisis.', disposition: 'believes in duty, open to how minds break' },
    { seat: 2, name: 'Grace Nkemdirim', age: 37, occupation: 'hospital pharmacist', background: 'Fills these exact prescriptions daily; knows interaction risk tables cold.', disposition: 'laser-focused on the medication evidence' },
    { seat: 3, name: 'Sal DiBenedetto', age: 54, occupation: 'plumbing contractor', background: 'Father of four; wary of expert witnesses who charge by the hour.', disposition: 'blunt, skeptical of both hired psychiatrists' },
    { seat: 4, name: 'Hannah Ostrander', age: 31, occupation: 'new mother on leave from accounting', background: 'Eight months postpartum herself; knows the sleepless dread firsthand.', disposition: 'deep empathy, determined not to let it decide for her' },
    { seat: 5, name: 'Wendell Gray', age: 59, occupation: 'probation officer', background: 'Twenty-five years judging who is dangerous and who is sick.', disposition: 'pragmatic about accountability and treatment' },
    { seat: 6, name: 'Celia Vasquez', age: 43, occupation: 'elementary school teacher', background: 'Teaches five-year-olds; the victims\' ages sit heavy on her.', disposition: 'fights to keep grief from becoming verdict' },
    { seat: 7, name: 'Douglas Finch', age: 48, occupation: 'actuary', background: 'Prices rare events professionally; 1-2 per 1000 births is a number he can work with.', disposition: 'coldly rational, follows base rates and burdens' },
    { seat: 8, name: 'Maeve Callahan', age: 62, occupation: 'retired psychiatric nurse', background: 'Decades on inpatient wards; has seen psychosis hide inside competence.', disposition: 'authoritative on symptoms, careful not to testify herself' },
    { seat: 9, name: 'Jerome Watts', age: 35, occupation: 'freight dispatcher', background: 'Lost a cousin to suicide; thinks about what warnings get missed.', disposition: 'quiet, attentive to the treatment timeline' },
    { seat: 10, name: 'Patricia Yune', age: 51, occupation: 'small-claims mediator', background: 'Settles disputes by finding what each side must concede.', disposition: 'consensus-builder, presses for precise findings' },
    { seat: 11, name: 'Colin Brody', age: 27, occupation: 'personal trainer', background: 'Uses resistance bands professionally; the physical details are vivid to him.', disposition: 'concrete thinker, needs the mechanics to add up' },
    { seat: 12, name: 'Eleanor Sachs', age: 70, occupation: 'retired family-court clerk', background: 'A career watching families at their worst without losing faith in law.', disposition: 'measured, insists on the McHoul standard as written' },
  ],
  researchHint: 'Commonwealth v. Lindsay Clancy, Plymouth Superior 2383CR00199 — ON TRIAL as of August 2026 before Sullivan, J. Refresh testimony, rulings, and filings from official sources; NEVER surface any real-world verdict, jury developments, or media sentiment to jurors — the simulation must remain strictly outcome-blind.',
};
